[build]
  command = "npm run build"
  publish = "dist"  # Ensure this matches your Vite output directory

[settings]
  base = "/"  # Set the base path

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
